#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allpre
runParallel $(getApplication)
runApplication python3 ../../evalLogCalcFixedIter.py log.$(getApplication)

#------------------------------------------------------------------------------
