# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Test installation of EESSI test suite with 'pip install'
on: [push, pull_request, workflow_dispatch]
permissions: read-all
jobs:
  test_pip_install:
    # ubuntu <= 20.04 is required for python 3.6
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
        - name: Check out repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
          with:
            persist-credentials: false

        - name: Set up Python
          uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install setuptools
          run: |
            if [[ "${{ matrix.python-version }}" == "3.6" ]]; then
              # system installed setuptools version in RHEL8 and CO7
              python -m pip install --user setuptools==39.2.0
            fi

        - name: Install ReFrame
          run: |
            python -m pip install --user ReFrame-HPC

        - name: Install EESSI test suite with 'pip install'
          run: |
            # install from source distribution tarball, to test release as published on PyPI
            rm -rf dist
            python setup.py sdist
            ls dist

            python -m pip install --user dist/eessi*.tar.gz
            find $HOME/.local

            # make sure we are not in the source directory
            cd $HOME

            python --version
            python -m pip --version
            python -c 'import setuptools; print("setuptools", setuptools.__version__)'

            python -c 'import eessi.testsuite.utils'
            python -c 'import eessi.testsuite.tests.apps'
